timeout: 1
graphics: no
# randomize_memory: yes
verbose: yes
interface_branding: 
interface_help_hidden: yes
editor_enabled: no
serial: yes

/Molt OS
    protocol: limine
    kernel_path: boot():/boot/kernel.bin
    module_path: boot():/boot/initramfs.cpio
    module_string: Initramfs (lz4)
    cmdline: fwtype=${FW_TYPE}
