/* Automatically generated clean stubs for kernel building */
#include <stddef.h>
extern int rump_init(void);

__attribute__((weak)) void rumpns_kmem_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mi_vector_hash(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kern_assert(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strchr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strlen(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_popcount(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_printf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_panic(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strtoumax(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strtoimax(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_memchr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_memcmp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strncmp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_explicit_memset(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__netbsd_keccakf1600(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_memcpy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ppath_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ppath_component_extant_dec(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ppath_component_extant_inc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ppath_extant_dec(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ppath_extant_inc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ppath_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_copy_mutable(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_get(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_set(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_bool_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_bool_true(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_data_copy_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_data_create_copy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_data_size(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_data_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_copy_mutable(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_get(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_create_signed(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_create_unsigned(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_signed_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_unsigned(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_unsigned_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_type(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_string_copy_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_string_create_copy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_string_size(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_string_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strcpy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kern_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kern_malloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_add(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_data_create_nocopy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_int16_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_int32_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_int64_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_int8_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_intptr_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_int_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_longlong_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_long_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_schar_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_short_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uchar_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uint16_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uint32_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uint64_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uint8_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uintptr_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_uint_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_ulonglong_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_ulong_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_ushort_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_string_create_nocopy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_snprintf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_hook_set(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_hook_unset(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_ioctl_50_hook(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strlcpy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_adjtime1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_clock_getres1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_clock_gettime1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_clock_settime1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyin(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyout(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_dogetitimer(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_dosetitimer(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_dotimer_gettime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_dotimer_settime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getmicroboottime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getrusage1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_authorize_system(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_microtime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nanosleep1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_settimeofday1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_syscall_disestablish(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_syscall_establish(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_createv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vec_ntp_gettime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vec_ntp_timestatus(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kevent1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pollcommon(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selcommon(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_uidmatch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_listen_scope(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_unlisten_scope(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_deregister(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_eval(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_extensions_vfs_start(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_extensions_vfs_stop(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_extensions_vfs_sysctl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_register(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_lookup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_geteuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strcasecmp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpreempt_disable(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpreempt_disabled(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpreempt_enable(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pmap_clear_attrs(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_clean_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_page_clear_dirty(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_page_dirty_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_page_set_dirty(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_owner_locked_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_x86_curcpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_gang_lookup_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_gang_lookup_node_reverse(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_gang_lookup_tagged_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_gang_lookup_tagged_node_reverse(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_enosys(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_clear_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_empty_tagged_tree_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_empty_tree_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_fini_tree(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_get_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_init_tree(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_set_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_lock_held(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_obj_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_obj_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_write_held(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ubc_purge(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_loanbreak(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_array_advance(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_array_fill_and_peek(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_array_fini(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_array_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagelock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagelookup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagemarkdirty(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_unbusy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pageunlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pageunwire(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagewire(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_wait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_dec_uint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_inc_uint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chgsemcnt(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyinstr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cprng_fast32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_broadcast(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_has_waiters(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_timedwait_sig(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fbadop_ioctl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fbadop_write(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_abort(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_affix(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_allocfile(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_close(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_getfile(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_putfile(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fnullop_fcntl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fnullop_kqfilter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fnullop_poll(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fnullop_restart(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hashdone(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hashinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_getegid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_zalloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_owned(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nanotime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strcmp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_teardown(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ts2timo(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uiomove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_x86_curlwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_compat_modstat_80_hook(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_authorize_process(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_get(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kernconfig_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kernconfig_unlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_stat(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_autoload(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_builtins(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_hook_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_hook_tryenter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_list(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_load(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_unload(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cprng_strong(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entropy_extract(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entropy_ready(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nist_sha256_hash_drbg_generate(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nist_sha256_hash_drbg_instantiate(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nist_sha256_hash_drbg_reseed(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_preempt_point(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sigispending(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_user_cprng(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_and_uint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_or_uint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_set_exclose(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktrace_on(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_genio(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_geniov(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_point(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_memset(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_psignal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_cas_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_cas_ptr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_swap_ptr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_blake2s_final(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_blake2s_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_blake2s_update(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kern_cprng(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_intr_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_intr_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_membar_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_murmurhash2(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nullop(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_membar_producer(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_wait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_wait_sig(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_get(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_put(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_trace_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_trace_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chglwpcnt(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chgproccnt(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_clone(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_getgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_getgroups(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_getsvgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_getsvuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_getuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_ngroups(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_setegid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_seteuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_setgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_setgroups(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_setsvgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_setsvuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_setuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_proc_setgroups(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_log(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_crmod_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_crmod_leave(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_enterpgrp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_find(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strncpy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_allbetsareoff_setid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_cred_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_cred_put(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_etfs_register(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_etfs_register_withsize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_etfs_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_kernelfsym_load(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_curlwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_newlwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_releaselwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_rfork(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_switch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_sysent_usenative(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_module_fini(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_module_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_schedule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_uio_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_uio_getoff(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_uio_getresid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_uio_setup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_unschedule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_nomodule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_syscall(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_seterrno(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___adjtime50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_clock_getcpuclockid2(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___clock_getres50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___clock_gettime50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_clock_nanosleep(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___clock_settime50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_close(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_dup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_dup2(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_fcntl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_fktrace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_flock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_fpathconf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___fstat50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getegid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_geteuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getgid_with_egid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getgroups(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___getitimer50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___getlogin(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getpgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getpgrp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getpid_with_ppid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getppid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getrandom(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getrlimit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getsid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___gettimeofday50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_getuid_with_euid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_ioctl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_issetugid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___kevent100(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_kqueue(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_kqueue1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_modctl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___nanosleep50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_pipe(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_pipe2(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_poll(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___pollts50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___posix_fadvise50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___pselect50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_read(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_readv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_reboot(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___select50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setegid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_seteuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setgroups(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___setitimer50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___setlogin(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setpgid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setregid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setreuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setrlimit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setsid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___settimeofday50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_setuid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___sysctl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_timer_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_timer_delete(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_timer_getoverrun(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___timer_gettime50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys___timer_settime50(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_utrace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_write(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_writev(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_syscall_boot_establish(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_curlwp_hypercall(void) { /* Dummy Stub */ }
__attribute__((weak)) void cv_broadcast(void) { /* Dummy Stub */ }
__attribute__((weak)) void cv_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void cv_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void cv_timedwait(void) { /* Dummy Stub */ }
__attribute__((weak)) void _kernel_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void _kernel_unlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void membar_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void mutex_spin_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void mutex_spin_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_closef(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyoutstr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_dup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_dup2(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_set_foclose(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_maxfiles(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pipe1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vnode_to_path(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_halt(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_pending(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_schedule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_setfunc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getnanotime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getnanouptime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_itimerfix(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_itimer_transition(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_itimespecfix(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpause(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpsignal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_spin_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_spin_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_resettodr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_softint_establish(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_softint_schedule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tc_getfrequency(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tc_setclock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tick(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_time_adjtime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_timecounter_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_timespecaddok(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_timespecsubok(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tshzto(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tshztoup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tstohz(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hexdigits(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pmatch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_panicstr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vpanic(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__init_once(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_append_empty_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_append_encoded_cstring(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_append_end_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_append_start_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_intern_decode_string(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_equals(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_object_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_retain(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_xml_intern_find_tag(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rb_tree_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rb_tree_insert_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rb_tree_remove_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vsnprintf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_dec_32_nv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_inc_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_inc_32_nv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_stack_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_stack_pop(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_stack_push(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_append_cstring(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rb_tree_find_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strtoll(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strtoull(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_allocator_nointr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_externalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_mmap_anon(void) { /* Dummy Stub */ }
__attribute__((weak)) void w(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kern_realloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_array_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_bool_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_data_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_dictionary_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_number_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_string_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_memmove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_create_with_capacity(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_end_line(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_start_line(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_intern_match(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_intern_skip_whitespace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_object_externalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_object_internalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_iterator_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_string_externalize_internal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__prop_extern_append_char(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strtoul(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cold(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_symbol(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_sym_lookup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_wbinvd(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc_broadcast(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc_wait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kcpuset_attached(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kcpuset_running(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kcpuset_set(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_allproc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_reset(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_stop(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_intr_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_softintr_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_signal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_timedwait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hz(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kthread_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kthread_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_syncobj(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pgrp_find(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_get_paddr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_put_paddr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_preempt(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_preempt_needed(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_syncobj(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_trace_is_enabled(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uio_setup_sysspace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmexp_pagesize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_debug(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chacha_const32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hexdump(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_error(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chacha_ref_impl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chacha_selftest(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_chacha_stream(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entropy_epoch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_evcnt_attach_dynamic(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_getref(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_putref(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_get_bool(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_dec_uint_nv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_membar_acquire(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pmap_page_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_obj_setlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagealloc_strat(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_page_array_clear(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagedeactivate(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagefree(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagegetdirty(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pagewait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__rw_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_coherency_unit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_gettimeleft(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_inittimeleft(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_klist_fini(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_klist_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_klist_insert(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_klist_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_knote(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_obj_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sigsuspendsetup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sigsuspendteardown(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_block(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_changepri(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_enqueue(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_lendpri(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_unsleep(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sleepq_wake(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_syncobj_noowner(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_add_int(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cv_is_valid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fgetown(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fownsignal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fsetown(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kernel_map(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_knote_set_eof(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_obj_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_obj_hold(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_seldestroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selnotify(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selrecord(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selrecord_knote(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selremove_knote(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_km_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_km_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_info_list(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mp_online(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ncpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_spllower(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_splraise(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_xc_highpri(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kthread_fpu_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_arena(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_schedppq(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_kick_pdaemon(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_km_kmem_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_km_kmem_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_workqueue_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_workqueue_enqueue(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_addrulwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_calcru(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getmicrotime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_find(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nanouptime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tvtohz(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_foreach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc_encode_ipl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_pctr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc_barrier(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_boothowto(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cnflush(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cnputc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_constty(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_xname(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kern_reboot(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_log_open(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_logputchar(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_logwakeup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp0(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_msgbufenabled(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_msgbufp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_sesshold(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_sessrele(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_read_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_read_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_spldebug_stop(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tputchar(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ttycheckoutq(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_reboot(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_shutting_down(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_time_adjusted(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_inc_uint_nv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__kernel_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__kernel_unlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_meta_arena(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_va_arena(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mutex_tryenter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ratecheck(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_copyout(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_time__uptime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vmem_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vmem_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vtophys(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vmem_xcreate(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc_unicast(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_devenodev(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_mibio(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nommap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_relock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_unlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ttyvenodev(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_machdep(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_reloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_renamespace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ksyms_getval_unlocked(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ksyms_modload(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ksyms_modunload(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_base(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_map(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_km_protect(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vprintf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_nativeabi_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_allocator_kmem(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strnlen(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_and_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_or_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_popcount32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getmicrouptime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_copyinstr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_get_expose_address(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hash_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_query(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_bdevsw(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_bdevsw0(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cdevsw(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cdevsw0(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_detach_commit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_lookup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_lookup_acquire(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_devsw_conv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_devsw_conv0(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_strdupsize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_localcount_acquire(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_localcount_drain(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_localcount_fini(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_localcount_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_localcount_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_max_bdevsws(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_max_cdevsws(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_max_devsw_convs(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_bdevsws(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_cdevsws(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getticks(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kcpuset_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpreempt(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_evcnt_detach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nist_sha256_hash_drbg_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_nist_sha256_hash_drbg_initialize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_SHA256_Final(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_SHA256_Init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_SHA256_Update(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kcopy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kernel_pmap_ptr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc0(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_vmspace_getref(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ucas_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ucas_64(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ufetch_16(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ufetch_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ufetch_64(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ufetch_8(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ustore_16(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ustore_32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ustore_64(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__ustore_8(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_io(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmspace_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_debug_dev(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_error_dev(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_get_error_count(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_naive(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_normal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_normal_dev(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cfattachinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cfdata(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cfdriver_list_initial(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cfroots(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_call_generic(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_cfdriver(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_handle(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_is_active(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_parent(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_private(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_properties(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_register(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_device_register_post_config(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__kernel_locked_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kthread_join(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pdevinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_printf_nolog(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_array_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_get_string(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_and_rel(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_string(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_string_nocopy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_uint16(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_add_uint32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_attach_source(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strlist_match(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_strlist_pmatch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_twiddle(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_bool_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_bool(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_data(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_int32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_int64(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_uint32(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_set_uint64(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_number_size(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_attach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_cfattach_attach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_cfdata_attach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_cfdriver_attach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_probe(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_search(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_add_long(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_add_long_nv(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hashstat_register(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_maxcpus(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_unlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_getptr_remote(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_alllwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aprint_verbose(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_swap_uint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_membar_consumer(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ntp_update_second(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_blake2s(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copystr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_mib(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_add_data(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_basenode_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_getmodel(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_domainname(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_domainnamelen(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hostname(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hostnamelen(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_machine(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_machine_arch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ncpuonline(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_osrelease(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ostype(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_physmem(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_version(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_emul_netbsd(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kernconfig_is_held(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_syscall(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktr_sysret(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sys_nosys(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_binuptime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_defcorename(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_maxlwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_maxproc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_uidmatch(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rw_tryenter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sched_nice(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmexp_pagemask(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmexp_pageshift(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_map_protect(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyin_proc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyin_vmspace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getcwd_common(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_hold(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_ismember_gid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_topcred(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_cred_toucred(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lim_setcorename(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_eprio(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_need_userret(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_in_read_section(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_perform(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rulwps(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ruspace(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_siginit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_domain_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_fini(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_getspecific(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_key_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_key_delete(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_setspecific(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_map_flags(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tty_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_availmem(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_init_limits(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_resident_count(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmspace_addref(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmspace_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns__mutex_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_eopnotsupp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_evcnt_attach_static(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_affix(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_find_section(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_load_mem(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kobj_unload(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_init_md(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_get_keysym(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_iterator(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_dictionary_keysym_value(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_object_iterator_next(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_time__second(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvmexp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_biglock_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_bootcpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_consdev_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_cpu_attach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_cpus_bootstrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_giantlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_hyperentropy_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_intr_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump__lwproc_alloclwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_curlwp_clear(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_curlwp_set(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_lwproc_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_allevents(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_init_cpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_startup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_config_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyright(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cprng_fast_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cprng_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_lookup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_devsw_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_enxio(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_evcnt_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_exec_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_sys_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_initmsgbuf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_inittimecounter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_iostat_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kcpuset_sysinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kernconfig_lock_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kmem_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kprintf_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kqueue_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ksyms_addsyms_explicit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ksyms_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktrinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_loginit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_initspecific(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwpinit_specificdata(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_builtin_add(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_builtin_remove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_hook_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_module_init_class(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ntp_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_once_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_percpu_init_cpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pipe_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pnbuf_cache(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_cpu_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc0_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_find_raw(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_procinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_procinit_sysctl(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_prop_kern_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_psref_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_resource_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_init_softint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_selsysinit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sigcantmask(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_softint_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_finalize(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_threadpools_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_time_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uao_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uid_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_pageout(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_ra_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vmem_rehash_start(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc__highpri_intr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_xc_init_cpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_scheduler_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_sysent(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_thread_allow(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_thread_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_tsleep_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_clock_gettime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_daemonize_begin(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_daemonize_done(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_dl_bootstrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_dprintf(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_getparam(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_user_schedule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_user_unschedule(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_clone(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kheapsort(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_seltrue(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_seltrue_kqfilter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uao_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uao_detach(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uao_reference(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ubc_uiomove(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_add_data_sync(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rndsource_setcb(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_getrandom(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_getnanoboottime(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_putchar(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fs_filtops(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sig_filtops(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_consttime_memequal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entpool_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entpool_enter_nostir(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entpool_extract(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entpool_selftest(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_entpool_stir(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_authorize_device(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_rnd_ioctl32_50_hook(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_seltrue_filtops(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_SHA1Final(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_SHA1Init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_SHA1Update(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_atomic_cas_uint(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_filedesc0(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_knote_fdclose(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kpgsignal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pgid_in_session(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sysctl_file_marker_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tablefull(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_callout_hardclock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_initclocks(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ptimer_tick(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sched_schedclock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_sched_tick(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_setstatclockrate(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tc_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tc_ticktock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_tickadj(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_cpu_makeclockframe(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_hardclock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_initclocks(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_profhz(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_schedhz(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_stathz(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_schedlock_cv_signal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_schedlock_cv_wait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_threads(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_clock_sleep(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_signal(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_wait_nowrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_enter_nowrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_broadcast(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_thread_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_thread_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_thread_join(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_secmodel_nsecmodels(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_yield(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_has_waiters(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_timedwait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_cv_wait(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_owner(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_spin_p(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_mutex_tryenter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_destroy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_downgrade(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_enter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_exit(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_held(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_tryenter(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_rw_tryupgrade(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_aobj_pager(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_copyout_proc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_format_bytes(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mtsleep(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pmap_resident_count(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_bootstrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_cache_reclaim(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_drain(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pool_subsystem_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_insert_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_lookup_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_radix_tree_remove_node(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vmem_create(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_vmem_subsystem_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_wakeup(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_sysproxy_ops(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_anonmmap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_malloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_unmap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_vfs_drainbufs(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_kernel_bigunwrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_kernel_bigwrap(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_vmspace_local(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_cpu_setmodel(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_initproc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_mi_cpu_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_softint_run(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_schedule_cpu(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_schedule_cpu_interlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_unschedule_cpu1(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_unschedule_cpu_interlock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_doexithooks(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_copy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_hold(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fd_share(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_fstrans_lwp_dtor(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_kauth_proc_fork(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktrace_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_ktrderef(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lim_addref(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lim_free(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_lwp_finispecific(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_alloc(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_alloc_lwpid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_finispecific(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_free_lwpid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_free_mem(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_free_pid(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_proc_leavepgrp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pstatscopy(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pstatsfree(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_unruntime_lock(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_proc_vfs_init(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_proc_vfs_release(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_curlwp(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_curlwpop(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_specificdata_getspecific_unlocked(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_kill(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_doshutdownhooks(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_pserialize_not_in_read_section(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpns_uvm_default_mapaddr(void) { /* Dummy Stub */ }
__attribute__((weak)) void rump_sysent_nomodbits(void) { /* Dummy Stub */ }
__attribute__((weak)) void rumpuser_exit(void) { /* Dummy Stub */ }
int __wrap_rump_init(void) {
    // Force GCC to load a full 64-bit absolute address into a register
    int (*volatile long_rump_init)(void) = &rump_init;
    return long_rump_init();
}
