#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <stdbool.h>

#define MAX_DEVICES 128
#define MAX_LINE_LEN 512

typedef struct {
    char name[64];
    char type[64];
    char ops[64];
    char include_path[256];
} Device;

Device devices[MAX_DEVICES];
int device_count = 0;

// Helper to trim whitespace/newlines
void trim(char *str) {
    char *end = str + strlen(str) - 1;
    while (end >= str && (*end == ' ' || *end == '\n' || *end == '\r' || *end == '\t')) {
        *end = '\0';
        end--;
    }
}

// Parses a single tag value out of a line (e.g., "// name: zero" -> "zero")
bool parse_tag(const char *line, const char *tag, char *output) {
    char prefix[128];
    snprintf(prefix, sizeof(prefix), "// %s:", tag);
    char *loc = strstr(line, prefix);
    if (loc) {
        // Pointer to the start of the value
        char *value_start = loc + strlen(prefix);
        // Skip leading whitespace/tabs
        while (*value_start == ' ' || *value_start == '\t') {
            value_start++;
        }
        strcpy(output, value_start);
        trim(output);
        return true;
    }
    return false;
}

void parse_file(const char *dir_name, const char *rel_path) {
    char full_path[512];
    snprintf(full_path, sizeof(full_path), "%s/%s", dir_name, rel_path);

    FILE *file = fopen(full_path, "r");
    if (!file) return;

    char line[MAX_LINE_LEN];
    bool is_device = false;
    Device dev = {0};
    strcpy(dev.include_path, rel_path);

    while (fgets(line, sizeof(line), file)) {
        if (strstr(line, "//@devcom:device") || strstr(line, "// @devcom:device")) {
            is_device = true;
        }
        if (is_device) {
            parse_tag(line, "name", dev.name);
            parse_tag(line, "type", dev.type);
            parse_tag(line, "ops", dev.ops);
        }
    }
    fclose(file);

    if (is_device && strlen(dev.name) > 0 && strlen(dev.type) > 0 && strlen(dev.ops) > 0) {
        if (device_count < MAX_DEVICES) {
            devices[device_count++] = dev;
        }
    }
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <devfs_directory> <output_file.c>\n", argv[0]);
        return 1;
    }

    char *devfs_dir = argv[1];
    char *output_path = argv[2];

    DIR *dir = opendir(devfs_dir);
    if (!dir) {
        perror("Error opening devfs directory");
        return 1;
    }

    struct dirent *entry;
    // Scan devfs/ directory for subdirectories containing main.c
    while ((entry = readdir(dir)) != NULL) {
        if (entry->d_name[0] == '.') continue; // Skip . and ..

        char sub_path[512];
        snprintf(sub_path, sizeof(sub_path), "%s/%s", devfs_dir, entry->d_name);

        struct stat statbuf;
        if (stat(sub_path, &statbuf) == 0 && S_ISDIR(statbuf.st_mode)) {
            char main_c_rel[256];
            snprintf(main_c_rel, sizeof(main_c_rel), "%s/main.c", entry->d_name);
            parse_file(devfs_dir, main_c_rel);
        }
    }
    closedir(dir);

    // Write the output devfs.c file
    FILE *out = fopen(output_path, "w");
    if (!out) {
        perror("Error opening output file");
        return 1;
    }

    fprintf(out, "// AUTOMATICALLY GENERATED BY DEVCOM - DO NOT EDIT\n");
    fprintf(out, "#include <vfs.h>\n");
    fprintf(out, "#include <string.h>\n");
    fprintf(out, "#include <stdlib.h>\n");
    fprintf(out, "#include <devfs.h>\n\n");
    fprintf(out, "vfs_node_t* dev_root = NULL;\n\n");

    fprintf(out, "// --- Device Module Implementations ---\n");
    for (int i = 0; i < device_count; i++) {
        fprintf(out, "#include \"%s\"\n", devices[i].include_path);
    }
    fprintf(out, "\n");

    fprintf(out, "void devfs_init(void) {\n");
    fprintf(out, "    dev_root = vfs_create_node(\"dev\", VFS_DIRECTORY);\n");
    fprintf(out, "    if (!dev_root) return;\n");
    fprintf(out, "    vfs_add_child(root_node, dev_root);\n\n");

    for (int i = 0; i < device_count; i++) {
        fprintf(out, "    // Auto-registration for /dev/%s\n", devices[i].name);
        fprintf(out, "    vfs_node_t* %s_node = vfs_create_node(\"%s\", %s);\n", devices[i].name, devices[i].name, devices[i].type);
        fprintf(out, "    if (%s_node) {\n", devices[i].name);
        fprintf(out, "        %s_node->ops = &%s;\n", devices[i].name, devices[i].ops);
        fprintf(out, "        vfs_add_child(dev_root, %s_node);\n", devices[i].name);
        fprintf(out, "    }\n\n");
    }

    fprintf(out, "}\n");
    fclose(out);

    return 0;
}
