#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <stdbool.h>

#define MAX_NODES 128
#define MAX_LINE_LEN 512

typedef struct {
    char name[64];
    char type[64];
    char ops[64];
    char include_path[256];
} ProcNode;

ProcNode proc_nodes[MAX_NODES];
int node_count = 0;

void trim(char *str) {
    char *end = str + strlen(str) - 1;
    while (end >= str && (*end == ' ' || *end == '\n' || *end == '\r' || *end == '\t')) {
        *end = '\0';
        end--;
    }
}

bool parse_tag(const char *line, const char *tag, char *output) {
    char prefix[128];
    snprintf(prefix, sizeof(prefix), "// %s:", tag);
    char *loc = strstr(line, prefix);
    if (loc) {
        strcpy(output, loc + strlen(prefix));
        trim(output);
        return true;
    }
    return false;
}

void parse_file(const char *dir_name, const char *rel_path) {
    char full_path[512];
    snprintf(full_path, sizeof(full_path), "%s/%s", dir_name, rel_path);

    FILE *file = fopen(full_path, "r");
    if (!file) return;

    char line[MAX_LINE_LEN];
    bool is_proc_node = false;
    ProcNode node = {0};
    strcpy(node.include_path, rel_path);

    while (fgets(line, sizeof(line), file)) {
        if (strstr(line, "//@proccom:node") || strstr(line, "// @proccom:node")) {
            is_proc_node = true;
        }
        if (is_proc_node) {
            parse_tag(line, "name", node.name);
            parse_tag(line, "type", node.type);
            parse_tag(line, "ops", node.ops);
        }
    }
    fclose(file);

    if (is_proc_node && strlen(node.name) > 0 && strlen(node.type) > 0 && strlen(node.ops) > 0) {
        if (node_count < MAX_NODES) {
            proc_nodes[node_count++] = node;
        }
    }
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <procfs_directory> <output_file.c>\n", argv[0]);
        return 1;
    }

    char *procfs_dir = argv[1];
    char *output_path = argv[2];

    DIR *dir = opendir(procfs_dir);
    if (!dir) {
        perror("Error opening procfs directory");
        return 1;
    }

    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL) {
        if (entry->d_name[0] == '.') continue;

        char sub_path[512];
        snprintf(sub_path, sizeof(sub_path), "%s/%s", procfs_dir, entry->d_name);

        struct stat statbuf;
        if (stat(sub_path, &statbuf) == 0 && S_ISDIR(statbuf.st_mode)) {
            char main_c_rel[256];
            snprintf(main_c_rel, sizeof(main_c_rel), "%s/main.c", entry->d_name);
            parse_file(procfs_dir, main_c_rel);
        }
    }
    closedir(dir);

    FILE *out = fopen(output_path, "w");
    if (!out) {
        perror("Error opening output file");
        return 1;
    }

    fprintf(out, "// AUTOMATICALLY GENERATED BY PROCOM - DO NOT EDIT\n");
    fprintf(out, "#include <vfs.h>\n");
    fprintf(out, "#include <string.h>\n");
    fprintf(out, "#include <stdlib.h>\n");
    fprintf(out, "#include <procfs.h>\n\n");
    fprintf(out, "static vfs_node_t* proc_root = NULL;\n\n");

    fprintf(out, "// --- ProcFS Entry Implementations ---\n");
    for (int i = 0; i < node_count; i++) {
        fprintf(out, "#include \"%s\"\n", proc_nodes[i].include_path);
    }
    fprintf(out, "\n");

    // Dynamic handling: Custom root handlers for readdir to yield PIDs dynamically
    fprintf(out, "// Custom root filesystem overrides for /proc to intercept readdir\n");
    fprintf(out, "static vfs_node_ops_t proc_root_ops;\n\n");

    fprintf(out, "void procfs_init(void) {\n");
    fprintf(out, "    proc_root = vfs_create_node(\"proc\", VFS_DIRECTORY);\n");
    fprintf(out, "    if (!proc_root) return;\n");
    fprintf(out, "    \n");
    fprintf(out, "    // Setup standard root operations, then hook our dynamic reader\n");
    fprintf(out, "    proc_root_ops = *proc_root->ops; \n");
    fprintf(out, "    proc_root_ops.readdir = procfs_root_readdir; \n");
    fprintf(out, "    proc_root->ops = &proc_root_ops;\n\n");
    fprintf(out, "    vfs_add_child(root_node, proc_root);\n\n");

    for (int i = 0; i < node_count; i++) {
        fprintf(out, "    // Auto-registration for static entry: /proc/%s\n", proc_nodes[i].name);
        fprintf(out, "    vfs_node_t* %s_node = vfs_create_node(\"%s\", %s);\n", proc_nodes[i].name, proc_nodes[i].name, proc_nodes[i].type);
        fprintf(out, "    if (%s_node) {\n", proc_nodes[i].name);
        fprintf(out, "        %s_node->ops = &%s;\n", proc_nodes[i].name, proc_nodes[i].ops);
        fprintf(out, "        vfs_add_child(proc_root, %s_node);\n", proc_nodes[i].name);
        fprintf(out, "    }\n\n");
    }

    fprintf(out, "}\n");
    fclose(out);

    return 0;
}

