KBUILD_CPPFLAGS := -I$(srctree)/lib/ulibc/third-party/linenoise

subdir-y += hello
subdir-y += poweroff
subdir-y += dash
subdir-y += test_shell
subdir-y += ls
subdir-y += fuzz

#subdir-y += skeleton/
