KBUILD_CPPFLAGS := -I$(srctree)/lib/ulibc/third-party/zline
export KBUILD_CPPFLAGS

subdir-y += hello
subdir-y += poweroff
subdir-y += dash
subdir-y += test_shell
subdir-y += ls
subdir-y += shz
subdir-y += fuzz
subdir-y += ttytest
#subdir-y += insmod

#subdir-y += skeleton/
