name: Generate Languages used

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq golang git fonts-terminus fonts-inconsolata fonts-dejavu

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Tokei
        id: cache-tokei
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/tokei
          key: ${{ runner.os }}-tokei-bin

      - name: Install Tokei via Cargo
        if: steps.cache-tokei.outputs.cache-hit != 'true'
        run: cargo install tokei

      - name: Cache Freeze
        id: cache-freeze
        uses: actions/cache@v4
        with:
          path: ~/go/bin/freeze
          key: ${{ runner.os }}-freeze-bin

      - name: Install freeze
        if: steps.cache-freeze.outputs.cache-hit != 'true'
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin

          go install github.com/charmbracelet/freeze@latest

      - name: Generate Stats and Screenshot
        shell: bash
        run: |
          # Move to the workspace root
          cd "$GITHUB_WORKSPACE"
          
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          
          # Install freeze binary
          go install github.com/charmbracelet/freeze@latest
          
          mkdir -p Documentation/stats

          # Pipe tokei output into freeze
          tokei | freeze --language text \
            --theme "dracula" \
            --shadow.blur 20 \
            --padding 20 \
            --output Documentation/stats/stats.png

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Updated languages used stat."
          file_pattern: 'Documentation/stats/stats.png'
          commit_user_name: tokei-lang[bot]
          commit_user_email: tokei-lang@coder.is-a.dev
          commit_author: Tokei <tokei-lang@coder.is-a.dev>
